name: Syllable Website
description: Information on the iPhone app Syllable
url: http://syllableapp.com
markdown: redcarpet
pygments: true
exclude: [README.md, Rakefile, config.rb]
paginate: 15
paginate_path: "blog/page:num"
permalink: /blog/:title
